name: Interactive thumbnails
dependencies:
  - worker
npm:
  dependencies:
    paraviewweb: 2.5.25
    mout: 1.0.0  # mout, monologue, and hammer are internal dependencies of paraviewweb
    monologue.js: 0.3.5
    hammerjs: 2.0.8
    pv-web-viewer: "kitware/pv-web-viewer#master"
    # dependencies of pv-web-viewer
    antd: 3.0.0
    kw-doc: 1.1.1
    kw-web-suite: 5.0.1
    lodash: ^4.17.4
    postcss-variables: 1.1.1
    react: 16.1.1
    react-dom: 16.1.1
    vtk.js: 5.12.1
