name: Interactive thumbnails
dependencies:
  - worker
npm:
  dependencies:
    paraviewweb: 2.5.25
    mout: 1.0.0  # mout, monologue, and hammer are internal dependencies of paraviewweb
    monologue.js: 0.3.5
    hammerjs: 2.0.8
    pv-glance-embeddable: 0.6.0
